[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayUnattendXml"
MatchAction = "Relay"
RelayTargets = ["KeepUnattendXmlRegexRed"]
Description = "Look inside unattend.xml files for actual values."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = ["unattend\\.xml", 
"Autounattend\\.xml"]
Triage = "Green"

[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepUnattendXmlRegexRed"
MatchAction = "Snaffle"
Description = "Files with contents matching these regexen are very interesting."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["(?s)<AdministratorPassword>.{0,30}<Value>.*<\\/Value>", 
"(?s)<AutoLogon>.{0,30}<Value>.*<\\/Value>"]
Triage = "Red"