[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepSSHKeysByFileExtension"
MatchAction = "Snaffle"
Description = "SSHKeys"
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = [
    "\\.ppk", 
    ]
Triage = "Black"
