[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "CertContentByEnding"
MatchAction = "Relay"
RelayTargets = ["KeepInlinePrivateKey"]
Description = "Files ending like this will be grepped for private keys."
MatchLocation = "FileName"
WordListType = "EndsWith"
MatchLength = 0
WordList = [
        "_rsa", 
        "_dsa", 
        "_ed25519", 
        "_ecdsa"
]
Triage = "Green"