[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepRubyByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = [
"database\\.yml", 
"\\.secret_token\\.rb",
"knife\\.rb", 
"carrierwave\\.rb", 
"omniauth\\.rb", 
]
Triage = "Red"