[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepPasswordFilesByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = [
"passwords\\.txt", 
"pass\\.txt", 
"accounts\\.txt", 
"passwords\\.doc", 
"pass\\.doc", 
"accounts\\.doc", 
"passwords\\.xls", 
"pass\\.xls", 
"accounts\\.xls", 
"passwords\\.docx", 
"pass\\.docx", 
"accounts\\.docx", 
"passwords\\.xlsx", 
"pass\\.xlsx", 
"accounts\\.xlsx", 
"secrets\\.txt", 
"secrets\\.doc", 
"secrets\\.xls", 
"secrets\\.docx", 
"secrets\\.xlsx",
]
Triage = "Red"