[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayPerlByExtension"
MatchAction = "Relay"
RelayTargets = ["KeepPerlDbConnStrings",
"KeepAwsKeysInCode",
"KeepInlinePrivateKey",
"KeepPassOrKeyInCode",  "KeepSlackTokensInCode",
"KeepSqlAccountCreation" ]
Description = "Files with these extensions will be searched for Perl related strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.pl"]
Triage = "Green"
