[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepPassOrKeyInCode"
MatchAction = "Snaffle"
Description = "Files with contents matching these regexen are very interesting."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = [
"passwo?r?d\\s*=\\s*[\\'\\\"][^\\'\\\"]....", 
"[_\\-\\.]?api[_\\-\\.]?key", 
"[_\\-\\.]oauth\\s*=", 
"client_secret", 
]
Triage = "Red"