[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepMemDumpByExtension"
MatchAction = "Snaffle"
Description = "Files with these extensions are a little interesting."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.dmp"]
Triage = "Yellow"
