[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepCyberArkCredFile"
MatchAction = "Snaffle"
Description = "A description of what a rule does."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = [
        "CredFileType="
]
Triage = "Red"