[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepGitCredsByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = [
"\\.git-credentials", 
]
Triage = "Red"

