[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepNameContainsGreen"
MatchAction = "Snaffle"
Description = "A description of what a rule does."
MatchLocation = "FileName"
WordListType = "Contains"
MatchLength = 0
WordList = ["passw",
"secret",
"thycotic",
"cyberark"]
Triage = "Green"