[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepNixLocalHashesByName"
MatchAction = "Snaffle"
Description = "Files with these exact names are very very interesting."
MatchLocation = "FileName"
WordListType = "Exact"
MatchLength = 0
WordList = [ 
"shadow", 
"pwd\\.db", 
"passwd",]
Triage = "Black"