
[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepCSharpViewstateKeys"
MatchAction = "Snaffle"
Description = "Files with contents matching these regexen are very interesting."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = [
"validationkey\\s*=\\s*[\\'\\\"][^\\'\\\"]....", 
"decryptionkey\\s*=\\s*[\\'\\\"][^\\'\\\"]....", 
]
Triage = "Red" 
